boolean test_result = true
pipeline{
    agent any
    environment {
        Build_stage = 'yes'
    }
    stages{
            stage('Master Build'){
                steps{
                    script{
                        try{
                            echo 'hellow wolrd'
                            sh 'sleep 5'
                            sh 'exit 1'
                        }catch(Exception e){
                            echo "stage master failed"
                            test_result = false
                        }

                    }
                    
                }
            }   

            stage('slave1 Test'){
                steps{
                    script{
                        if (test_result == true){
                            echo "Master Build success ful so slave1 executed"
                            sh 'sleep 5'
                        }
                    }
                    
                }
            }
            stage('slave2  Depoly'){
                steps{
                    script{
                        if (test_result == false){
                            echo "Master Build failed so slave 2 executed"
                            sh 'sleep 5'
                        }
                }
            }
        }
    }
}
