pipeline {
        agent any
        environment {
                  Build_stage = 'yes'
                }
          stages {
                stage('slave2 Build') { 
                       
                    steps{
                          sh 'sleep 5'
                        
                        }
                }                    
                   
                stage('slave1 Test') { 
                        script{
                                env.Build_stage = 'ravi'
                        }
                     steps{
                           sh 'sleep 5'
                        
                        }
                     }
                stage('Master deploy') { 
                        
                    steps{
                           sh 'sleep 5'
                           // echo "{$Depoly_To}"
                           echo "${env.Build_stage}"  
                        }
                   
                    }
            }
    }
